[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "cd backend && npm install",
  "cd frontend && npm install --include=dev"
]

[phases.build]
cmds = [
  "cd frontend && npm run build || true"
]

[start]
cmd = "cd backend && node server.js"
